# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a867ec78007af68d15444639cab879fc79a1b272ac770b17a969eca58c5b92a8820e7eb6ceaed739e454b7e39b67d639d2f7944afc2c5e53bd7371bc56f738b

test:
  secret_key_base: ca553c4bafb700283ce0907a8e62e04ec4f32e748bef974a62cd8f416cc81b8155985804eaf9f42e46be46bd82085412b3c0c059a3fd27f5523425491a0382fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
